## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

2023-05-04 18:18:58.799220: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN','NAME'])

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
bin_app = application_df['APPLICATION_TYPE'].value_counts()

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(bin_app[bin_app<500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
bin_class = application_df['CLASSIFICATION'].value_counts()

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
bin_class = bin_class[bin_class>1]

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(bin_class[bin_class<500].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1458
C7000      777
C1370        1
C1236        1
C2190        1
C4200        1
C5200        1
C6100        1
C2600        1
C1248        1
C1580        1
C1820        1
C1900        1
C2570        1
C1283        1
C3700        1
C2500        1
C1570        1
C2380        1
C1732        1
C1728        1
C2170        1
C4120        1
C8210        1
C4500        1
C1245        1
C2561        1
C2150        1
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype = float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [10]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
X = application_df.drop('IS_SUCCESSFUL', axis=1).values
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state= 78)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 16

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 568

 dense_1 (Dense)             (None, 16)                144

 dense_2 (Dense)             (None, 1)                 17

=================================================================
Total params: 729
Trainable params: 729
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [14]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15,epochs=100)

Epoch 1/100
684/684 [==============================] - 4s 3ms/step - loss: 0.6003 - accuracy: 0.7084 - val_loss: 0.5785 - val_accuracy: 0.7142
Epoch 2/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5687 - accuracy: 0.7282 - val_loss: 0.5681 - val_accuracy: 0.7248
Epoch 3/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5611 - accuracy: 0.7303 - val_loss: 0.5662 - val_accuracy: 0.7230
Epoch 4/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5570 - accuracy: 0.7317 - val_loss: 0.5653 - val_accuracy: 0.7232
Epoch 5/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5544 - accuracy: 0.7326 - val_loss: 0.5643 - val_accuracy: 0.7225
Epoch 6/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5526 - accuracy: 0.7347 - val_loss: 0.5644 - val_accuracy: 0.7217
Epoch 7/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5512 - accuracy: 0.7344 - val_loss: 0.5634 - val_accuracy: 0.7238
Epoch 8/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5506 - accuracy: 0.7346 - val_loss: 0.5620 - val_accuracy: 0.7230
Epoch 9/100
684/684 [==============================] - 5s 7ms/step - loss: 0.5493 - accuracy: 0.7347 - val_loss: 0.5628 - val_accuracy: 0.7217
Epoch 10/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5486 - accuracy: 0.7354 - val_loss: 0.5604 - val_accuracy: 0.7243
Epoch 11/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5480 - accuracy: 0.7352 - val_loss: 0.5612 - val_accuracy: 0.7240
Epoch 12/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5472 - accuracy: 0.7357 - val_loss: 0.5592 - val_accuracy: 0.7219
Epoch 13/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5465 - accuracy: 0.7349 - val_loss: 0.5624 - val_accuracy: 0.7217
Epoch 14/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5463 - accuracy: 0.7357 - val_loss: 0.5624 - val_accuracy: 0.7232
Epoch 15/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5453 - accuracy: 0.7366 - val_loss: 0.5637 - val_accuracy: 0.7214
Epoch 16/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5454 - accuracy: 0.7354 - val_loss: 0.5615 - val_accuracy: 0.7238
Epoch 17/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5450 - accuracy: 0.7353 - val_loss: 0.5614 - val_accuracy: 0.7235
Epoch 18/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5450 - accuracy: 0.7355 - val_loss: 0.5598 - val_accuracy: 0.7238
Epoch 19/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5444 - accuracy: 0.7355 - val_loss: 0.5609 - val_accuracy: 0.7225
Epoch 20/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5443 - accuracy: 0.7345 - val_loss: 0.5605 - val_accuracy: 0.7245
Epoch 21/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5443 - accuracy: 0.7351 - val_loss: 0.5575 - val_accuracy: 0.7248
Epoch 22/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5440 - accuracy: 0.7345 - val_loss: 0.5601 - val_accuracy: 0.7230
Epoch 23/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5437 - accuracy: 0.7365 - val_loss: 0.5608 - val_accuracy: 0.7214
Epoch 24/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5435 - accuracy: 0.7350 - val_loss: 0.5616 - val_accuracy: 0.7214
Epoch 25/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5440 - accuracy: 0.7360 - val_loss: 0.5611 - val_accuracy: 0.7194
Epoch 26/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5429 - accuracy: 0.7361 - val_loss: 0.5601 - val_accuracy: 0.7201
Epoch 27/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5432 - accuracy: 0.7355 - val_loss: 0.5620 - val_accuracy: 0.7217
Epoch 28/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5425 - accuracy: 0.7360 - val_loss: 0.5622 - val_accuracy: 0.7222
Epoch 29/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5430 - accuracy: 0.7361 - val_loss: 0.5612 - val_accuracy: 0.7230
Epoch 30/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5423 - accuracy: 0.7356 - val_loss: 0.5623 - val_accuracy: 0.7227
Epoch 31/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5424 - accuracy: 0.7364 - val_loss: 0.5595 - val_accuracy: 0.7232
Epoch 32/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5425 - accuracy: 0.7367 - val_loss: 0.5592 - val_accuracy: 0.7209
Epoch 33/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5423 - accuracy: 0.7360 - val_loss: 0.5607 - val_accuracy: 0.7232
Epoch 34/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5424 - accuracy: 0.7365 - val_loss: 0.5629 - val_accuracy: 0.7222
Epoch 35/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5418 - accuracy: 0.7366 - val_loss: 0.5597 - val_accuracy: 0.7217
Epoch 36/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5421 - accuracy: 0.7364 - val_loss: 0.5626 - val_accuracy: 0.7235
Epoch 37/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5419 - accuracy: 0.7362 - val_loss: 0.5603 - val_accuracy: 0.7225
Epoch 38/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5422 - accuracy: 0.7358 - val_loss: 0.5598 - val_accuracy: 0.7238
Epoch 39/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5419 - accuracy: 0.7364 - val_loss: 0.5634 - val_accuracy: 0.7201
Epoch 40/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5419 - accuracy: 0.7366 - val_loss: 0.5622 - val_accuracy: 0.7212
Epoch 41/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5417 - accuracy: 0.7367 - val_loss: 0.5647 - val_accuracy: 0.7199
Epoch 42/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5417 - accuracy: 0.7367 - val_loss: 0.5602 - val_accuracy: 0.7230
Epoch 43/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5417 - accuracy: 0.7372 - val_loss: 0.5608 - val_accuracy: 0.7212
Epoch 44/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5414 - accuracy: 0.7373 - val_loss: 0.5632 - val_accuracy: 0.7227
Epoch 45/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5412 - accuracy: 0.7370 - val_loss: 0.5599 - val_accuracy: 0.7219
Epoch 46/100
684/684 [==============================] - 7s 10ms/step - loss: 0.5412 - accuracy: 0.7371 - val_loss: 0.5617 - val_accuracy: 0.7232
Epoch 47/100
684/684 [==============================] - 10s 14ms/step - loss: 0.5413 - accuracy: 0.7369 - val_loss: 0.5611 - val_accuracy: 0.7238
Epoch 48/100
684/684 [==============================] - 7s 10ms/step - loss: 0.5409 - accuracy: 0.7363 - val_loss: 0.5609 - val_accuracy: 0.7230
Epoch 49/100
684/684 [==============================] - 9s 14ms/step - loss: 0.5412 - accuracy: 0.7369 - val_loss: 0.5630 - val_accuracy: 0.7219
Epoch 50/100
684/684 [==============================] - 8s 11ms/step - loss: 0.5412 - accuracy: 0.7370 - val_loss: 0.5639 - val_accuracy: 0.7232
Epoch 51/100
684/684 [==============================] - 9s 14ms/step - loss: 0.5411 - accuracy: 0.7372 - val_loss: 0.5631 - val_accuracy: 0.7207
Epoch 52/100
684/684 [==============================] - 8s 12ms/step - loss: 0.5409 - accuracy: 0.7376 - val_loss: 0.5631 - val_accuracy: 0.7222
Epoch 53/100
684/684 [==============================] - 8s 11ms/step - loss: 0.5410 - accuracy: 0.7368 - val_loss: 0.5638 - val_accuracy: 0.7232
Epoch 54/100
684/684 [==============================] - 9s 14ms/step - loss: 0.5406 - accuracy: 0.7367 - val_loss: 0.5636 - val_accuracy: 0.7196
Epoch 55/100
684/684 [==============================] - 14s 20ms/step - loss: 0.5406 - accuracy: 0.7368 - val_loss: 0.5636 - val_accuracy: 0.7217
Epoch 56/100
684/684 [==============================] - 12s 18ms/step - loss: 0.5411 - accuracy: 0.7369 - val_loss: 0.5633 - val_accuracy: 0.7214
Epoch 57/100
684/684 [==============================] - 12s 18ms/step - loss: 0.5407 - accuracy: 0.7386 - val_loss: 0.5661 - val_accuracy: 0.7186
Epoch 58/100
684/684 [==============================] - 8s 11ms/step - loss: 0.5408 - accuracy: 0.7376 - val_loss: 0.5648 - val_accuracy: 0.7219
Epoch 59/100
684/684 [==============================] - 8s 11ms/step - loss: 0.5404 - accuracy: 0.7368 - val_loss: 0.5647 - val_accuracy: 0.7238
Epoch 60/100
684/684 [==============================] - 9s 14ms/step - loss: 0.5405 - accuracy: 0.7372 - val_loss: 0.5630 - val_accuracy: 0.7245
Epoch 61/100
684/684 [==============================] - 8s 12ms/step - loss: 0.5406 - accuracy: 0.7381 - val_loss: 0.5677 - val_accuracy: 0.7212
Epoch 62/100
684/684 [==============================] - 8s 12ms/step - loss: 0.5406 - accuracy: 0.7381 - val_loss: 0.5634 - val_accuracy: 0.7232
Epoch 63/100
684/684 [==============================] - 8s 12ms/step - loss: 0.5405 - accuracy: 0.7384 - val_loss: 0.5670 - val_accuracy: 0.7227
Epoch 64/100
684/684 [==============================] - 7s 11ms/step - loss: 0.5405 - accuracy: 0.7386 - val_loss: 0.5661 - val_accuracy: 0.7204
Epoch 65/100
684/684 [==============================] - 7s 11ms/step - loss: 0.5405 - accuracy: 0.7377 - val_loss: 0.5644 - val_accuracy: 0.7222
Epoch 66/100
684/684 [==============================] - 7s 10ms/step - loss: 0.5402 - accuracy: 0.7388 - val_loss: 0.5653 - val_accuracy: 0.7217
Epoch 67/100
684/684 [==============================] - 8s 12ms/step - loss: 0.5404 - accuracy: 0.7380 - val_loss: 0.5647 - val_accuracy: 0.7227
Epoch 68/100
684/684 [==============================] - 8s 12ms/step - loss: 0.5400 - accuracy: 0.7375 - val_loss: 0.5698 - val_accuracy: 0.7209
Epoch 69/100
684/684 [==============================] - 7s 10ms/step - loss: 0.5405 - accuracy: 0.7381 - val_loss: 0.5660 - val_accuracy: 0.7238
Epoch 70/100
684/684 [==============================] - 7s 10ms/step - loss: 0.5402 - accuracy: 0.7381 - val_loss: 0.5656 - val_accuracy: 0.7232
Epoch 71/100
684/684 [==============================] - 6s 9ms/step - loss: 0.5403 - accuracy: 0.7391 - val_loss: 0.5662 - val_accuracy: 0.7209
Epoch 72/100
684/684 [==============================] - 7s 10ms/step - loss: 0.5399 - accuracy: 0.7380 - val_loss: 0.5644 - val_accuracy: 0.7222
Epoch 73/100
684/684 [==============================] - 8s 12ms/step - loss: 0.5400 - accuracy: 0.7387 - val_loss: 0.5689 - val_accuracy: 0.7212
Epoch 74/100
684/684 [==============================] - 12s 18ms/step - loss: 0.5403 - accuracy: 0.7382 - val_loss: 0.5667 - val_accuracy: 0.7207
Epoch 75/100
684/684 [==============================] - 12s 18ms/step - loss: 0.5399 - accuracy: 0.7381 - val_loss: 0.5674 - val_accuracy: 0.7227
Epoch 76/100
684/684 [==============================] - 9s 13ms/step - loss: 0.5398 - accuracy: 0.7383 - val_loss: 0.5641 - val_accuracy: 0.7222
Epoch 77/100
684/684 [==============================] - 7s 10ms/step - loss: 0.5401 - accuracy: 0.7389 - val_loss: 0.5665 - val_accuracy: 0.7225
Epoch 78/100
684/684 [==============================] - 14s 20ms/step - loss: 0.5398 - accuracy: 0.7386 - val_loss: 0.5638 - val_accuracy: 0.7230
Epoch 79/100
684/684 [==============================] - 11s 16ms/step - loss: 0.5396 - accuracy: 0.7383 - val_loss: 0.5662 - val_accuracy: 0.7212
Epoch 80/100
684/684 [==============================] - 12s 17ms/step - loss: 0.5399 - accuracy: 0.7386 - val_loss: 0.5691 - val_accuracy: 0.7219
Epoch 81/100
684/684 [==============================] - 12s 18ms/step - loss: 0.5396 - accuracy: 0.7375 - val_loss: 0.5682 - val_accuracy: 0.7204
Epoch 82/100
684/684 [==============================] - 11s 16ms/step - loss: 0.5396 - accuracy: 0.7389 - val_loss: 0.5638 - val_accuracy: 0.7225
Epoch 83/100
684/684 [==============================] - 17s 25ms/step - loss: 0.5397 - accuracy: 0.7387 - val_loss: 0.5663 - val_accuracy: 0.7212
Epoch 84/100
684/684 [==============================] - 16s 23ms/step - loss: 0.5398 - accuracy: 0.7389 - val_loss: 0.5664 - val_accuracy: 0.7204
Epoch 85/100
684/684 [==============================] - 12s 17ms/step - loss: 0.5395 - accuracy: 0.7380 - val_loss: 0.5682 - val_accuracy: 0.7238
Epoch 86/100
684/684 [==============================] - 22s 33ms/step - loss: 0.5397 - accuracy: 0.7390 - val_loss: 0.5662 - val_accuracy: 0.7196
Epoch 87/100
684/684 [==============================] - 19s 27ms/step - loss: 0.5396 - accuracy: 0.7389 - val_loss: 0.5688 - val_accuracy: 0.7219
Epoch 88/100
684/684 [==============================] - 15s 21ms/step - loss: 0.5396 - accuracy: 0.7391 - val_loss: 0.5652 - val_accuracy: 0.7201
Epoch 89/100
684/684 [==============================] - 18s 27ms/step - loss: 0.5393 - accuracy: 0.7393 - val_loss: 0.5668 - val_accuracy: 0.7204
Epoch 90/100
684/684 [==============================] - 13s 19ms/step - loss: 0.5393 - accuracy: 0.7388 - val_loss: 0.5664 - val_accuracy: 0.7204
Epoch 91/100
684/684 [==============================] - 10s 14ms/step - loss: 0.5394 - accuracy: 0.7390 - val_loss: 0.5653 - val_accuracy: 0.7232
Epoch 92/100
684/684 [==============================] - 7s 11ms/step - loss: 0.5395 - accuracy: 0.7388 - val_loss: 0.5671 - val_accuracy: 0.7248
Epoch 93/100
684/684 [==============================] - 7s 10ms/step - loss: 0.5395 - accuracy: 0.7394 - val_loss: 0.5642 - val_accuracy: 0.7225
Epoch 94/100
684/684 [==============================] - 7s 11ms/step - loss: 0.5389 - accuracy: 0.7384 - val_loss: 0.5682 - val_accuracy: 0.7235
Epoch 95/100
684/684 [==============================] - 7s 10ms/step - loss: 0.5393 - accuracy: 0.7385 - val_loss: 0.5662 - val_accuracy: 0.7204
Epoch 96/100
684/684 [==============================] - 7s 10ms/step - loss: 0.5390 - accuracy: 0.7389 - val_loss: 0.5682 - val_accuracy: 0.7232
Epoch 97/100
684/684 [==============================] - 9s 13ms/step - loss: 0.5391 - accuracy: 0.7380 - val_loss: 0.5680 - val_accuracy: 0.7199
Epoch 98/100
684/684 [==============================] - 8s 12ms/step - loss: 0.5390 - accuracy: 0.7387 - val_loss: 0.5646 - val_accuracy: 0.7219
Epoch 99/100
684/684 [==============================] - 6s 9ms/step - loss: 0.5396 - accuracy: 0.7390 - val_loss: 0.5653 - val_accuracy: 0.7225
Epoch 100/100
684/684 [==============================] - 8s 11ms/step - loss: 0.5390 - accuracy: 0.7397 - val_loss: 0.5667 - val_accuracy: 0.7209

In [37]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

8575/8575 - 0s - loss: 0.5578 - acc: 0.7263
Loss: 0.557812534073699, Accuracy: 0.7262973785400391

In [38]:
# Export our model to HDF5 file
from google.colab import files

nn_model.save('/content/Alphabet_Soup_model3.h5')
files.download('/content/Alphabet_Soup_model3.h5')